version = "3.11.1"
runner.dialect = scala213

maxColumn = 120
align.preset = more
align.multiline = false

project.git = true

rewrite.rules = [Imports, RedundantBraces, RedundantParens, SortModifiers]
rewrite.imports.sort = ascii
rewrite.imports.groups = [
  ["java\\..*", "javax\\..*"],
  ["scala\\..*"],
  ["_root_\\.cats\\..*"],
  ["dev\\..*"],
  [".*"]
]
